using System.Threading;
using System.Threading.Tasks;

namespace ATS5.Application.ProductTest
{
    /// <summary>
    /// Handles the legacy ProductTest MES upload point that must run after local product test saves.
    /// </summary>
    public interface IProductTestMesUploadGateway
    {
        /// <summary>
        /// Uploads MES data after local save and updates the legacy MES index status using WinForms rules.
        /// </summary>
        /// <param name="logGuid">Legacy log identifier generated by the execution core.</param>
        /// <param name="channel">Legacy test channel number.</param>
        /// <param name="isCompileAndInit">Whether dynamic script compilation and device initialization succeeded.</param>
        /// <param name="cancellationToken">Token used to cancel the upload wrapper.</param>
        /// <returns>The MES result value forwarded to AutoTestMESResult.</returns>
        Task<bool> UploadAfterLocalSaveAsync(
            ulong logGuid,
            ushort channel,
            bool isCompileAndInit,
            CancellationToken cancellationToken);
    }
}
