using System;
using System.Collections.Generic;
using System.Linq;

namespace ATS5.Application.ProductTest
{
    /// <summary>
    /// Captures the legacy ProductTest execution result required for MES upload and AutoTest callbacks.
    /// </summary>
    public sealed class ProductTestSessionResult
    {
        /// <summary>
        /// Gets the legacy log identifier generated by the execution core.
        /// </summary>
        public ulong LogGuid { get; }

        /// <summary>
        /// Gets the legacy test channel number.
        /// </summary>
        public ushort Channel { get; }

        /// <summary>
        /// Gets the raw per-barcode test results from the legacy test core.
        /// </summary>
        public IReadOnlyList<string> TestResults { get; }

        /// <summary>
        /// Gets a value indicating whether script compilation and device initialization succeeded.
        /// </summary>
        public bool IsCompileAndInit { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductTestSessionResult"/> class.
        /// </summary>
        /// <param name="logGuid">Legacy log identifier generated by the execution core.</param>
        /// <param name="channel">Legacy test channel number.</param>
        /// <param name="testResults">Raw per-barcode test results.</param>
        /// <param name="isCompileAndInit">Whether dynamic script compilation and device initialization succeeded.</param>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="testResults"/> is null.</exception>
        public ProductTestSessionResult(
            ulong logGuid,
            ushort channel,
            IEnumerable<string> testResults,
            bool isCompileAndInit)
        {
            LogGuid = logGuid;
            Channel = channel;
            TestResults = (testResults ?? throw new ArgumentNullException(nameof(testResults))).ToArray();
            IsCompileAndInit = isCompileAndInit;
        }
    }
}
